package org.abc.domain;

import java.util.Date;

public class Categoria implements Comparable<Object>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.categoria.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    private Integer idCategoria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.categoria.nombre
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.categoria.estado
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.categoria.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    private Date fechaReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.categoria.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    private Date fechaMod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.categoria.id_categoria
     *
     * @return the value of public.categoria.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public Integer getIdCategoria() {
        return idCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.categoria.id_categoria
     *
     * @param idCategoria the value for public.categoria.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.categoria.nombre
     *
     * @return the value of public.categoria.nombre
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.categoria.nombre
     *
     * @param nombre the value for public.categoria.nombre
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.categoria.estado
     *
     * @return the value of public.categoria.estado
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.categoria.estado
     *
     * @param estado the value for public.categoria.estado
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.categoria.fecha_reg
     *
     * @return the value of public.categoria.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public Date getFechaReg() {
        return fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.categoria.fecha_reg
     *
     * @param fechaReg the value for public.categoria.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.categoria.fecha_mod
     *
     * @return the value of public.categoria.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public Date getFechaMod() {
        return fechaMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.categoria.fecha_mod
     *
     * @param fechaMod the value for public.categoria.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:11:30 BOT 2020
     */
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    
    @Override
    public int compareTo(Object object) {
    	Categoria cat=(Categoria)object;
    	return this.idCategoria.compareTo(cat.getIdCategoria());
	}
//    @Override
//	public boolean equals(Object obj) {
//		if (obj instanceof Categoria && ((Categoria) obj).getIdCategoria() == this.idCategoria)
//			return true;
//		return false;
//
//	}
}