package org.abc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Compra implements Comparable<Object>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.id_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Integer idCompra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.id_persona
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Integer idPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.id_usuario
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.total
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private BigDecimal total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.estado
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private String estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.fecha_reg
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Date fechaReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.fecha_mod
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Date fechaMod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.fecha
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Date fecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.compra.hora
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	private Date hora;
	private String nomPersona;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.id_compra
	 * @return  the value of public.compra.id_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Integer getIdCompra() {
		return idCompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.id_compra
	 * @param idCompra  the value for public.compra.id_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setIdCompra(Integer idCompra) {
		this.idCompra = idCompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.id_persona
	 * @return  the value of public.compra.id_persona
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Integer getIdPersona() {
		return idPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.id_persona
	 * @param idPersona  the value for public.compra.id_persona
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.id_usuario
	 * @return  the value of public.compra.id_usuario
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.id_usuario
	 * @param idUsuario  the value for public.compra.id_usuario
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.total
	 * @return  the value of public.compra.total
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public BigDecimal getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.total
	 * @param total  the value for public.compra.total
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.estado
	 * @return  the value of public.compra.estado
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.estado
	 * @param estado  the value for public.compra.estado
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setEstado(String estado) {
		this.estado = estado == null ? null : estado.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.fecha_reg
	 * @return  the value of public.compra.fecha_reg
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Date getFechaReg() {
		return fechaReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.fecha_reg
	 * @param fechaReg  the value for public.compra.fecha_reg
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.fecha_mod
	 * @return  the value of public.compra.fecha_mod
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Date getFechaMod() {
		return fechaMod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.fecha_mod
	 * @param fechaMod  the value for public.compra.fecha_mod
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.fecha
	 * @return  the value of public.compra.fecha
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.fecha
	 * @param fecha  the value for public.compra.fecha
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.compra.hora
	 * @return  the value of public.compra.hora
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public Date getHora() {
		return hora;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.compra.hora
	 * @param hora  the value for public.compra.hora
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getNomPersona() {
		return nomPersona;
	}

	public void setNomPersona(String nomPersona) {
		this.nomPersona = nomPersona;
	}
	@Override
    public int compareTo(Object object) {
    	Compra cmp=(Compra)object;
    	return this.idCompra.compareTo(cmp.getIdCompra());
	}
	
}