package org.abc.domain;

import java.math.BigDecimal;

public class DetalleVenta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.id_detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private Integer idDetalleVenta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.id_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private Integer idVenta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.id_producto
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private Integer idProducto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.cantidad
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private Integer cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.precio_unitario
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private BigDecimal precioUnitario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.importe
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private BigDecimal importe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.detalle_venta.id_detalle_compra
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	private Integer idDetalleCompra;
	
	private String detProducto;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.id_detalle_venta
	 * @return  the value of public.detalle_venta.id_detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public Integer getIdDetalleVenta() {
		return idDetalleVenta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.id_detalle_venta
	 * @param idDetalleVenta  the value for public.detalle_venta.id_detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setIdDetalleVenta(Integer idDetalleVenta) {
		this.idDetalleVenta = idDetalleVenta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.id_venta
	 * @return  the value of public.detalle_venta.id_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public Integer getIdVenta() {
		return idVenta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.id_venta
	 * @param idVenta  the value for public.detalle_venta.id_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setIdVenta(Integer idVenta) {
		this.idVenta = idVenta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.id_producto
	 * @return  the value of public.detalle_venta.id_producto
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public Integer getIdProducto() {
		return idProducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.id_producto
	 * @param idProducto  the value for public.detalle_venta.id_producto
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.cantidad
	 * @return  the value of public.detalle_venta.cantidad
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.cantidad
	 * @param cantidad  the value for public.detalle_venta.cantidad
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.precio_unitario
	 * @return  the value of public.detalle_venta.precio_unitario
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public BigDecimal getPrecioUnitario() {
		return precioUnitario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.precio_unitario
	 * @param precioUnitario  the value for public.detalle_venta.precio_unitario
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.importe
	 * @return  the value of public.detalle_venta.importe
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public BigDecimal getImporte() {
		return importe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.importe
	 * @param importe  the value for public.detalle_venta.importe
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.detalle_venta.id_detalle_compra
	 * @return  the value of public.detalle_venta.id_detalle_compra
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public Integer getIdDetalleCompra() {
		return idDetalleCompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.detalle_venta.id_detalle_compra
	 * @param idDetalleCompra  the value for public.detalle_venta.id_detalle_compra
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	public void setIdDetalleCompra(Integer idDetalleCompra) {
		this.idDetalleCompra = idDetalleCompra;
	}

	public String getDetProducto() {
		return detProducto;
	}

	public void setDetProducto(String detProducto) {
		this.detProducto = detProducto;
	}
	
}