package org.abc.domain;

import java.util.Date;

public class Laboratorio implements Comparable<Object>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.id_laboratorio
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private Integer idLaboratorio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.id_usuario
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.nombre
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.telefono
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.estado
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private String estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.fecha_reg
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private Date fechaReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.laboratorio.fecha_mod
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	private Date fechaMod;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.id_laboratorio
	 * @return  the value of public.laboratorio.id_laboratorio
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public Integer getIdLaboratorio() {
		return idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.id_laboratorio
	 * @param idLaboratorio  the value for public.laboratorio.id_laboratorio
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setIdLaboratorio(Integer idLaboratorio) {
		this.idLaboratorio = idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.id_usuario
	 * @return  the value of public.laboratorio.id_usuario
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.id_usuario
	 * @param idUsuario  the value for public.laboratorio.id_usuario
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.nombre
	 * @return  the value of public.laboratorio.nombre
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.nombre
	 * @param nombre  the value for public.laboratorio.nombre
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre == null ? null : nombre.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.telefono
	 * @return  the value of public.laboratorio.telefono
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.telefono
	 * @param telefono  the value for public.laboratorio.telefono
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono == null ? null : telefono.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.estado
	 * @return  the value of public.laboratorio.estado
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.estado
	 * @param estado  the value for public.laboratorio.estado
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setEstado(String estado) {
		this.estado = estado == null ? null : estado.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.fecha_reg
	 * @return  the value of public.laboratorio.fecha_reg
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public Date getFechaReg() {
		return fechaReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.fecha_reg
	 * @param fechaReg  the value for public.laboratorio.fecha_reg
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.laboratorio.fecha_mod
	 * @return  the value of public.laboratorio.fecha_mod
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public Date getFechaMod() {
		return fechaMod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.laboratorio.fecha_mod
	 * @param fechaMod  the value for public.laboratorio.fecha_mod
	 * @mbg.generated  Tue Sep 15 17:08:00 BOT 2020
	 */
	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Override
    public int compareTo(Object object) {
    	Laboratorio lab=(Laboratorio)object;
    	return this.idLaboratorio.compareTo(lab.getIdLaboratorio());
	}
}