package org.abc.domain;

import java.util.Date;

public class Persona implements Comparable<Object>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Integer idPersona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.nombre
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.ap
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String ap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.am
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String am;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.telefono
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.direccion
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String direccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Date fechaReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.persona.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Date fechaMod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.id_persona
     *
     * @return the value of public.persona.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.id_persona
     *
     * @param idPersona the value for public.persona.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.id_usuario
     *
     * @return the value of public.persona.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.id_usuario
     *
     * @param idUsuario the value for public.persona.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.nombre
     *
     * @return the value of public.persona.nombre
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.nombre
     *
     * @param nombre the value for public.persona.nombre
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim().toUpperCase();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.ap
     *
     * @return the value of public.persona.ap
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getAp() {
        return ap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.ap
     *
     * @param ap the value for public.persona.ap
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setAp(String ap) {
        this.ap = ap == null ? null : ap.trim().toUpperCase();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.am
     *
     * @return the value of public.persona.am
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getAm() {
        return am;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.am
     *
     * @param am the value for public.persona.am
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setAm(String am) {
        this.am = am == null ? null : am.trim().toUpperCase();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.telefono
     *
     * @return the value of public.persona.telefono
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.telefono
     *
     * @param telefono the value for public.persona.telefono
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono == null ? null : telefono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.direccion
     *
     * @return the value of public.persona.direccion
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.direccion
     *
     * @param direccion the value for public.persona.direccion
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.estado
     *
     * @return the value of public.persona.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.estado
     *
     * @param estado the value for public.persona.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.fecha_reg
     *
     * @return the value of public.persona.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Date getFechaReg() {
        return fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.fecha_reg
     *
     * @param fechaReg the value for public.persona.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.persona.fecha_mod
     *
     * @return the value of public.persona.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Date getFechaMod() {
        return fechaMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.persona.fecha_mod
     *
     * @param fechaMod the value for public.persona.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public String getNomCompleto() {
        return this.nombre+" "+this.ap+" "+this.am;
    }
    @Override
    public int compareTo(Object object) {
    	Persona persona=(Persona)object;
    	return this.idPersona.compareTo(persona.getIdPersona());
	}
}