package org.abc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public ProductoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdProductoIsNull() {
            addCriterion("id_producto is null");
            return (Criteria) this;
        }

        public Criteria andIdProductoIsNotNull() {
            addCriterion("id_producto is not null");
            return (Criteria) this;
        }

        public Criteria andIdProductoEqualTo(Integer value) {
            addCriterion("id_producto =", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotEqualTo(Integer value) {
            addCriterion("id_producto <>", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoGreaterThan(Integer value) {
            addCriterion("id_producto >", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_producto >=", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoLessThan(Integer value) {
            addCriterion("id_producto <", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoLessThanOrEqualTo(Integer value) {
            addCriterion("id_producto <=", value, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoIn(List<Integer> values) {
            addCriterion("id_producto in", values, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotIn(List<Integer> values) {
            addCriterion("id_producto not in", values, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoBetween(Integer value1, Integer value2) {
            addCriterion("id_producto between", value1, value2, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdProductoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_producto not between", value1, value2, "idProducto");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIsNull() {
            addCriterion("id_categoria is null");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIsNotNull() {
            addCriterion("id_categoria is not null");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaEqualTo(Integer value) {
            addCriterion("id_categoria =", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotEqualTo(Integer value) {
            addCriterion("id_categoria <>", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaGreaterThan(Integer value) {
            addCriterion("id_categoria >", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_categoria >=", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaLessThan(Integer value) {
            addCriterion("id_categoria <", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaLessThanOrEqualTo(Integer value) {
            addCriterion("id_categoria <=", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIn(List<Integer> values) {
            addCriterion("id_categoria in", values, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotIn(List<Integer> values) {
            addCriterion("id_categoria not in", values, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria between", value1, value2, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria not between", value1, value2, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioIsNull() {
            addCriterion("id_laboratorio is null");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioIsNotNull() {
            addCriterion("id_laboratorio is not null");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioEqualTo(Integer value) {
            addCriterion("id_laboratorio =", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioNotEqualTo(Integer value) {
            addCriterion("id_laboratorio <>", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioGreaterThan(Integer value) {
            addCriterion("id_laboratorio >", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_laboratorio >=", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioLessThan(Integer value) {
            addCriterion("id_laboratorio <", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioLessThanOrEqualTo(Integer value) {
            addCriterion("id_laboratorio <=", value, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioIn(List<Integer> values) {
            addCriterion("id_laboratorio in", values, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioNotIn(List<Integer> values) {
            addCriterion("id_laboratorio not in", values, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioBetween(Integer value1, Integer value2) {
            addCriterion("id_laboratorio between", value1, value2, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdLaboratorioNotBetween(Integer value1, Integer value2) {
            addCriterion("id_laboratorio not between", value1, value2, "idLaboratorio");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("id_usuario is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("id_usuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(Integer value) {
            addCriterion("id_usuario =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(Integer value) {
            addCriterion("id_usuario <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(Integer value) {
            addCriterion("id_usuario >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_usuario >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(Integer value) {
            addCriterion("id_usuario <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("id_usuario <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<Integer> values) {
            addCriterion("id_usuario in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<Integer> values) {
            addCriterion("id_usuario not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("id_usuario between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("id_usuario not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andPrincipioIsNull() {
            addCriterion("principio is null");
            return (Criteria) this;
        }

        public Criteria andPrincipioIsNotNull() {
            addCriterion("principio is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipioEqualTo(String value) {
            addCriterion("principio =", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioNotEqualTo(String value) {
            addCriterion("principio <>", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioGreaterThan(String value) {
            addCriterion("principio >", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioGreaterThanOrEqualTo(String value) {
            addCriterion("principio >=", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioLessThan(String value) {
            addCriterion("principio <", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioLessThanOrEqualTo(String value) {
            addCriterion("principio <=", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioLike(String value) {
            addCriterion("principio like", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioNotLike(String value) {
            addCriterion("principio not like", value, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioIn(List<String> values) {
            addCriterion("principio in", values, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioNotIn(List<String> values) {
            addCriterion("principio not in", values, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioBetween(String value1, String value2) {
            addCriterion("principio between", value1, value2, "principio");
            return (Criteria) this;
        }

        public Criteria andPrincipioNotBetween(String value1, String value2) {
            addCriterion("principio not between", value1, value2, "principio");
            return (Criteria) this;
        }

        public Criteria andPresentacionIsNull() {
            addCriterion("presentacion is null");
            return (Criteria) this;
        }

        public Criteria andPresentacionIsNotNull() {
            addCriterion("presentacion is not null");
            return (Criteria) this;
        }

        public Criteria andPresentacionEqualTo(String value) {
            addCriterion("presentacion =", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionNotEqualTo(String value) {
            addCriterion("presentacion <>", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionGreaterThan(String value) {
            addCriterion("presentacion >", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionGreaterThanOrEqualTo(String value) {
            addCriterion("presentacion >=", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionLessThan(String value) {
            addCriterion("presentacion <", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionLessThanOrEqualTo(String value) {
            addCriterion("presentacion <=", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionLike(String value) {
            addCriterion("presentacion like", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionNotLike(String value) {
            addCriterion("presentacion not like", value, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionIn(List<String> values) {
            addCriterion("presentacion in", values, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionNotIn(List<String> values) {
            addCriterion("presentacion not in", values, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionBetween(String value1, String value2) {
            addCriterion("presentacion between", value1, value2, "presentacion");
            return (Criteria) this;
        }

        public Criteria andPresentacionNotBetween(String value1, String value2) {
            addCriterion("presentacion not between", value1, value2, "presentacion");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIsNull() {
            addCriterion("unidad_medida is null");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIsNotNull() {
            addCriterion("unidad_medida is not null");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaEqualTo(String value) {
            addCriterion("unidad_medida =", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotEqualTo(String value) {
            addCriterion("unidad_medida <>", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaGreaterThan(String value) {
            addCriterion("unidad_medida >", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaGreaterThanOrEqualTo(String value) {
            addCriterion("unidad_medida >=", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLessThan(String value) {
            addCriterion("unidad_medida <", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLessThanOrEqualTo(String value) {
            addCriterion("unidad_medida <=", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLike(String value) {
            addCriterion("unidad_medida like", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotLike(String value) {
            addCriterion("unidad_medida not like", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIn(List<String> values) {
            addCriterion("unidad_medida in", values, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotIn(List<String> values) {
            addCriterion("unidad_medida not in", values, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaBetween(String value1, String value2) {
            addCriterion("unidad_medida between", value1, value2, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotBetween(String value1, String value2) {
            addCriterion("unidad_medida not between", value1, value2, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNull() {
            addCriterion("cantidad is null");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNotNull() {
            addCriterion("cantidad is not null");
            return (Criteria) this;
        }

        public Criteria andCantidadEqualTo(Integer value) {
            addCriterion("cantidad =", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotEqualTo(Integer value) {
            addCriterion("cantidad <>", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThan(Integer value) {
            addCriterion("cantidad >", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("cantidad >=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThan(Integer value) {
            addCriterion("cantidad <", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThanOrEqualTo(Integer value) {
            addCriterion("cantidad <=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadIn(List<Integer> values) {
            addCriterion("cantidad in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotIn(List<Integer> values) {
            addCriterion("cantidad not in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadBetween(Integer value1, Integer value2) {
            addCriterion("cantidad between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotBetween(Integer value1, Integer value2) {
            addCriterion("cantidad not between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("public.producto.estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("estado like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("estado not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andFechaRegIsNull() {
            addCriterion("fecha_reg is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegIsNotNull() {
            addCriterion("fecha_reg is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegEqualTo(Date value) {
            addCriterion("fecha_reg =", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegNotEqualTo(Date value) {
            addCriterion("fecha_reg <>", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegGreaterThan(Date value) {
            addCriterion("fecha_reg >", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_reg >=", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegLessThan(Date value) {
            addCriterion("fecha_reg <", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegLessThanOrEqualTo(Date value) {
            addCriterion("fecha_reg <=", value, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegIn(List<Date> values) {
            addCriterion("fecha_reg in", values, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegNotIn(List<Date> values) {
            addCriterion("fecha_reg not in", values, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegBetween(Date value1, Date value2) {
            addCriterion("fecha_reg between", value1, value2, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaRegNotBetween(Date value1, Date value2) {
            addCriterion("fecha_reg not between", value1, value2, "fechaReg");
            return (Criteria) this;
        }

        public Criteria andFechaModIsNull() {
            addCriterion("fecha_mod is null");
            return (Criteria) this;
        }

        public Criteria andFechaModIsNotNull() {
            addCriterion("fecha_mod is not null");
            return (Criteria) this;
        }

        public Criteria andFechaModEqualTo(Date value) {
            addCriterion("fecha_mod =", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModNotEqualTo(Date value) {
            addCriterion("fecha_mod <>", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModGreaterThan(Date value) {
            addCriterion("fecha_mod >", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_mod >=", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModLessThan(Date value) {
            addCriterion("fecha_mod <", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModLessThanOrEqualTo(Date value) {
            addCriterion("fecha_mod <=", value, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModIn(List<Date> values) {
            addCriterion("fecha_mod in", values, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModNotIn(List<Date> values) {
            addCriterion("fecha_mod not in", values, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModBetween(Date value1, Date value2) {
            addCriterion("fecha_mod between", value1, value2, "fechaMod");
            return (Criteria) this;
        }

        public Criteria andFechaModNotBetween(Date value1, Date value2) {
            addCriterion("fecha_mod not between", value1, value2, "fechaMod");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.producto
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 17 20:46:50 BOT 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}