package org.abc.domain;

import java.util.Date;

public class Producto implements Comparable<Object>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.producto
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private String producto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.descripcion
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.estado
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.fec_caducidad
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private Date fecCaducidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.marca
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private Boolean marca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.parecedero
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    private Boolean parecedero;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id
     *
     * @return the value of public.producto.id
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id
     *
     * @param id the value for public.producto.id
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.producto
     *
     * @return the value of public.producto.producto
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public String getProducto() {
        return producto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.producto
     *
     * @param producto the value for public.producto.producto
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setProducto(String producto) {
        this.producto = producto == null ? null : producto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.descripcion
     *
     * @return the value of public.producto.descripcion
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.descripcion
     *
     * @param descripcion the value for public.producto.descripcion
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.estado
     *
     * @return the value of public.producto.estado
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.estado
     *
     * @param estado the value for public.producto.estado
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.fec_caducidad
     *
     * @return the value of public.producto.fec_caducidad
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public Date getFecCaducidad() {
        return fecCaducidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.fec_caducidad
     *
     * @param fecCaducidad the value for public.producto.fec_caducidad
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setFecCaducidad(Date fecCaducidad) {
        this.fecCaducidad = fecCaducidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.marca
     *
     * @return the value of public.producto.marca
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public Boolean getMarca() {
        return marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.marca
     *
     * @param marca the value for public.producto.marca
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setMarca(Boolean marca) {
        this.marca = marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.parecedero
     *
     * @return the value of public.producto.parecedero
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public Boolean getParecedero() {
        return parecedero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.parecedero
     *
     * @param parecedero the value for public.producto.parecedero
     *
     * @mbg.generated Sun Sep 06 19:32:10 BOT 2020
     */
    public void setParecedero(Boolean parecedero) {
        this.parecedero = parecedero;
    }
    
    @Override
    public int compareTo(Object object) {
    	Producto producto=(Producto)object;
    	return this.producto.compareTo(producto.getId().toString());
	}
}