package org.abc.domain;

import java.util.Date;

public class Producto implements Comparable<Object>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id_producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Integer idProducto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Integer idCategoria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id_laboratorio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Integer idLaboratorio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.id_usuario
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.principio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private String principio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.presentacion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private String presentacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.unidad_medida
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private String unidadMedida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.cantidad
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Integer cantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.descripcion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.estado
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Date fechaReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.producto.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    private Date fechaMod;
    private Categoria categoria;
    private Laboratorio laboratorio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id_producto
     *
     * @return the value of public.producto.id_producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id_producto
     *
     * @param idProducto the value for public.producto.id_producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id_categoria
     *
     * @return the value of public.producto.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Integer getIdCategoria() {
        return idCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id_categoria
     *
     * @param idCategoria the value for public.producto.id_categoria
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id_laboratorio
     *
     * @return the value of public.producto.id_laboratorio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Integer getIdLaboratorio() {
        return idLaboratorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id_laboratorio
     *
     * @param idLaboratorio the value for public.producto.id_laboratorio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setIdLaboratorio(Integer idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.id_usuario
     *
     * @return the value of public.producto.id_usuario
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.id_usuario
     *
     * @param idUsuario the value for public.producto.id_usuario
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.principio
     *
     * @return the value of public.producto.principio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getPrincipio() {
        return principio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.principio
     *
     * @param principio the value for public.producto.principio
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setPrincipio(String principio) {
        this.principio = principio == null ? null : principio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.presentacion
     *
     * @return the value of public.producto.presentacion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getPresentacion() {
        return presentacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.presentacion
     *
     * @param presentacion the value for public.producto.presentacion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion == null ? null : presentacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.unidad_medida
     *
     * @return the value of public.producto.unidad_medida
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getUnidadMedida() {
        return unidadMedida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.unidad_medida
     *
     * @param unidadMedida the value for public.producto.unidad_medida
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida == null ? null : unidadMedida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.cantidad
     *
     * @return the value of public.producto.cantidad
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.cantidad
     *
     * @param cantidad the value for public.producto.cantidad
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.descripcion
     *
     * @return the value of public.producto.descripcion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.descripcion
     *
     * @param descripcion the value for public.producto.descripcion
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.estado
     *
     * @return the value of public.producto.estado
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.estado
     *
     * @param estado the value for public.producto.estado
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.fecha_reg
     *
     * @return the value of public.producto.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Date getFechaReg() {
        return fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.fecha_reg
     *
     * @param fechaReg the value for public.producto.fecha_reg
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.producto.fecha_mod
     *
     * @return the value of public.producto.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public Date getFechaMod() {
        return fechaMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.producto.fecha_mod
     *
     * @param fechaMod the value for public.producto.fecha_mod
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Laboratorio getLaboratorio() {
		return laboratorio;
	}

	public void setLaboratorio(Laboratorio laboratorio) {
		this.laboratorio = laboratorio;
	}
    @Override
    public int compareTo(Object object) {
    	Producto cat=(Producto)object;
    	return this.idProducto.compareTo(cat.getIdProducto());
	}
    
}