package org.abc.domain;

import java.util.Date;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Integer idUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Integer idPersona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.login
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.clave
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String clave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Date fechaReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usuario.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    private Date fechaMod;
    private Persona persona;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.id_usuario
     *
     * @return the value of public.usuario.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.id_usuario
     *
     * @param idUsuario the value for public.usuario.id_usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.id_persona
     *
     * @return the value of public.usuario.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.id_persona
     *
     * @param idPersona the value for public.usuario.id_persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.login
     *
     * @return the value of public.usuario.login
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.login
     *
     * @param login the value for public.usuario.login
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.clave
     *
     * @return the value of public.usuario.clave
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getClave() {
        return clave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.clave
     *
     * @param clave the value for public.usuario.clave
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setClave(String clave) {
        this.clave = clave == null ? null : clave.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.estado
     *
     * @return the value of public.usuario.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.estado
     *
     * @param estado the value for public.usuario.estado
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.fecha_reg
     *
     * @return the value of public.usuario.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Date getFechaReg() {
        return fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.fecha_reg
     *
     * @param fechaReg the value for public.usuario.fecha_reg
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usuario.fecha_mod
     *
     * @return the value of public.usuario.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public Date getFechaMod() {
        return fechaMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usuario.fecha_mod
     *
     * @param fechaMod the value for public.usuario.fecha_mod
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
    
}