package org.abc.mapper;

import java.util.List;
import org.abc.domain.Compra;
import org.abc.domain.CompraExample;
import org.apache.ibatis.annotations.Param;

public interface CompraMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	long countByExample(CompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int deleteByExample(CompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int deleteByPrimaryKey(Integer idCompra);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int insert(Compra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int insertSelective(Compra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	List<Compra> selectByExample(CompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	Compra selectByPrimaryKey(Integer idCompra);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByExampleSelective(@Param("record") Compra record, @Param("example") CompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByExample(@Param("record") Compra record, @Param("example") CompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByPrimaryKeySelective(Compra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByPrimaryKey(Compra record);
}