package org.abc.mapper;

import java.math.BigDecimal;
import java.util.List;
import org.abc.domain.DetalleCompra;
import org.abc.domain.DetalleCompraExample;
import org.apache.ibatis.annotations.Param;

public interface DetalleCompraMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	long countByExample(DetalleCompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int deleteByExample(DetalleCompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int deleteByPrimaryKey(Integer idDetalleCompra);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int insert(DetalleCompra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int insertSelective(DetalleCompra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	List<DetalleCompra> selectByExample(DetalleCompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	DetalleCompra selectByPrimaryKey(Integer idDetalleCompra);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByExampleSelective(@Param("record") DetalleCompra record, @Param("example") DetalleCompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByExample(@Param("record") DetalleCompra record, @Param("example") DetalleCompraExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByPrimaryKeySelective(DetalleCompra record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_compra
	 * @mbg.generated  Fri Sep 18 15:30:47 BOT 2020
	 */
	int updateByPrimaryKey(DetalleCompra record);
	
	BigDecimal sumImporte(DetalleCompraExample example);
	
	List<DetalleCompra> selectDetCompraEnInventario(Integer idProducto);
}