package org.abc.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.abc.domain.DetalleCompraExample;
import org.abc.domain.DetalleVenta;
import org.abc.domain.DetalleVentaExample;
import org.apache.ibatis.annotations.Param;

public interface DetalleVentaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	long countByExample(DetalleVentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int deleteByExample(DetalleVentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int deleteByPrimaryKey(Integer idDetalleVenta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int insert(DetalleVenta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int insertSelective(DetalleVenta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	List<DetalleVenta> selectByExample(DetalleVentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	DetalleVenta selectByPrimaryKey(Integer idDetalleVenta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByExampleSelective(@Param("record") DetalleVenta record, @Param("example") DetalleVentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByExample(@Param("record") DetalleVenta record, @Param("example") DetalleVentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByPrimaryKeySelective(DetalleVenta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.detalle_venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByPrimaryKey(DetalleVenta record);
	
	BigDecimal sumImporte(DetalleVentaExample example);
}