package org.abc.mapper;

import java.util.List;
import org.abc.domain.Persona;
import org.abc.domain.PersonaExample;
import org.apache.ibatis.annotations.Param;

public interface PersonaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    long countByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int deleteByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int deleteByPrimaryKey(Integer idPersona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int insert(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int insertSelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    List<Persona> selectByExample(PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    Persona selectByPrimaryKey(Integer idPersona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByExampleSelective(@Param("record") Persona record, @Param("example") PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByExample(@Param("record") Persona record, @Param("example") PersonaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByPrimaryKeySelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.persona
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByPrimaryKey(Persona record);
}