package org.abc.mapper;

import java.util.List;
import org.abc.domain.Producto;
import org.abc.domain.ProductoExample;
import org.apache.ibatis.annotations.Param;

public interface ProductoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    long countByExample(ProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int deleteByExample(ProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int deleteByPrimaryKey(Integer idProducto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int insert(Producto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int insertSelective(Producto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    List<Producto> selectByExample(ProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    Producto selectByPrimaryKey(Integer idProducto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int updateByExampleSelective(@Param("record") Producto record, @Param("example") ProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int updateByExample(@Param("record") Producto record, @Param("example") ProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int updateByPrimaryKeySelective(Producto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.producto
     *
     * @mbg.generated Thu Sep 17 20:46:50 BOT 2020
     */
    int updateByPrimaryKey(Producto record);
}