package org.abc.mapper;

import java.util.List;
import org.abc.domain.Usuario;
import org.abc.domain.UsuarioExample;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    long countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int deleteByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    Usuario selectByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usuario
     *
     * @mbg.generated Mon Sep 14 10:24:56 BOT 2020
     */
    int updateByPrimaryKey(Usuario record);
}