package org.abc.mapper;

import java.util.List;
import org.abc.domain.Venta;
import org.abc.domain.VentaExample;
import org.apache.ibatis.annotations.Param;

public interface VentaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	long countByExample(VentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int deleteByExample(VentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int deleteByPrimaryKey(Integer idVenta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int insert(Venta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int insertSelective(Venta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	List<Venta> selectByExample(VentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	Venta selectByPrimaryKey(Integer idVenta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByExampleSelective(@Param("record") Venta record, @Param("example") VentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByExample(@Param("record") Venta record, @Param("example") VentaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByPrimaryKeySelective(Venta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.venta
	 * @mbg.generated  Sat Sep 19 19:28:04 BOT 2020
	 */
	int updateByPrimaryKey(Venta record);
}